# Generated by Django 2.2.4 on 2021-02-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAuthorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
