# Generated by Django 2.2.4 on 2021-02-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAuthorApp', '0002_author_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='notes',
        ),
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.ManyToManyField(related_name='publishers', to='booksAuthorApp.Book'),
        ),
    ]
